### ISSUE TITLE
[Arquillian Cube OpenShift] Implement resource provider for the OpenShift route

### ISSUE THREAD

**Issue by RadekKoubsky** [arquillian/arquillian-cube#744] opened 2017-06-27 15:22 UTC
It would be nice to have a resource provider for the OpenShift routes to inject them into a test class. 

An example of such solution:
```
@RunWith(Arquillian.class)
public class ExampleTest {
    @ArquillianResource
     OpenShiftClient client;

     @ArquillianResource
     Route route;
}
```

instead of getting a route using the openshift client:
```
final Route route = this.client.adapt(OpenShiftClient.class)
                .routes()
                .inNamespace(this.session.getNamespace())
                .withName(this.applicationName)
                .get();
```

**Comment by bartoszmajsak** [comment] 2017-06-29 07:41
Hey @RadekKoubsky. Thanks for suggesting this improvement. Would you be interested in providing PR for that? 

If you need some help discussing details of the implementation just ping me or @lordofthejars.

**Comment by RadekKoubsky** [comment] 2017-07-10 11:16
@bartoszmajsak Hi, I would love to work on Arquillian Cube. However, I have lot of prioritized items for our target release which is not focused on using Arquillian Cube (that is supposed to be for the future release, 1.1.0.Next in Jira). I will come back to this later on.

**Comment by spolti** [comment] 2017-07-10 18:53
I think we have this option on ce-arq (an extension of arquillian-cube).
Instead to use arquillianResource we use this to obtain the route based on the application name:
`   
@RouteURL("eap-app")
private URL url;`

https://github.com/jboss-openshift/ce-arq/blob/master/cube/src/main/java/org/jboss/arquillian/ce/cube/RouteURL.java

**Comment by lordofthejars** [comment] 2017-07-10 19:20
Then maybe we can try to reuse this inside cube

**Comment by spolti** [comment] 2017-07-11 14:41
@lordofthejars I'll try to do that, I just have to finish some some priorities.

**Comment by jwendell** [comment] 2017-07-12 13:37
dupe of #465?

**Closed** 2017-08-04 07:18 UTC
