### ISSUE TITLE
Message: Forbidden! User admin/192-168-64-17:8443 doesn't have permission..

### ISSUE THREAD

**Issue by cmoulliard** [arquillian/arquillian-cube#444] opened 2016-09-22 13:45 UTC
When this code is executed 

https://github.com/redhat-microservices/quick_swarm_camel-test/blob/arquillian-cube/src/test/java/io.obsidian.quickstart.swarm/OpenshiftIntegrationKT.java

using minishift as OpenShift platform, the following error is returned

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.obsidian.quickstart.swarm.OpenshiftIntegrationKT
Initializing Session:036cd06c-357a-486a-97b4-f12a4c52332f
Using Kubernetes at: https://192.168.64.17:8443/
Creating kubernetes resources inside namespace: itest-036cd06c-357a-486a-97b4-f12a4c52332f
if you use OpenShift then type this switch namespaces:     oc project itest-036cd06c-357a-486a-97b4-f12a4c52332f
if you use kubernetes then type this to switch namespaces: kubectl namespace itest-036cd06c-357a-486a-97b4-f12a4c52332f
Applying kubernetes configuration from: file:/Users/chmoulli/RedHat/GP/projects/redhat-microservices/quick_swarm_camel/target/classes/kubernetes.json
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.782 sec <<< FAILURE! - in io.obsidian.quickstart.swarm.OpenshiftIntegrationKT
io.obsidian.quickstart.swarm.OpenshiftIntegrationKT  Time elapsed: 2.781 sec  <<< ERROR!
java.lang.RuntimeException: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.64.17:8443/api/v1/namespaces/itest-8c7a3ac9-4607-44ea-98fc-ee19d0bc9ff9/services. Message: Forbidden! User admin/192-168-64-17:8443 doesn't have permission..
        at org.arquillian.cube.kubernetes.impl.SessionListener.start(SessionListener.java:138)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
        at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
        at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
        at org.arquillian.cube.kubernetes.impl.SuiteListener.start(SuiteListener.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
        at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
        at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
        at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:75)
        at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:115)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.64.17:8443/api/v1/namespaces/itest-8c7a3ac9-4607-44ea-98fc-ee19d0bc9ff9/services. Message: Forbidden! User admin/192-168-64-17:8443 doesn't have permission..
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:314)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:265)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:236)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:229)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:207)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:564)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:264)
        at io.fabric8.kubernetes.client.handlers.ServiceHandler.create(ServiceHandler.java:38)
        at io.fabric8.kubernetes.client.handlers.ServiceHandler.create(ServiceHandler.java:28)
        at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetDeleteRecreateApplicableImpl.apply(NamespaceVisitFromServerGetDeleteRecreateApplicableImpl.java:123)
        at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetDeleteRecreateApplicableImpl.apply(NamespaceVisitFromServerGetDeleteRecreateApplicableImpl.java:51)
        at org.arquillian.cube.kubernetes.impl.SessionListener.start(SessionListener.java:116)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
        at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
        at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
        at org.arquillian.cube.kubernetes.impl.SuiteListener.start(SuiteListener.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
        at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
        at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
        at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:75)
        at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:115)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)


Results :

Tests in error: 
  OpenshiftIntegrationKT.io.obsidian.quickstart.swarm.OpenshiftIntegrationKT » Runtime
```
Remark: This is strange as different system properties have been defined to use the default namespace

**Comment by iocanel** [comment] 2016-09-22 13:47
I've hit this too with minishift. I am pretty confident that its minishift specific. 
I am trying to see if there is something that it can be done on the cube side of things to work around it.

**Comment by cmoulliard** [comment] 2016-09-22 13:56
This is not minishift specific but Kubernetes related I think so ;-)

**Comment by lordofthejars** [comment] 2016-09-22 16:21
I have not tried with Cube, but with kubectl command I needed first to run `oc login` command to create a valid access token on config.json file.

**Comment by lordofthejars** [comment] 2016-09-23 07:15
@iocanel how are you using cube-kubernetes? Without using minishift? I still think that the problem is in the .kube/config file that needs to be filled correctly.

**Comment by iocanel** [comment] 2016-09-23 08:38
Yes, tried arquillian-cube-kubernetes against minishift and got the same error. It worked fine on minikube and on plain openshift.

**Comment by lordofthejars** [comment] 2016-09-23 08:40
hummm, does fabric8 kubernetes client (or in cube part) rad configuration from ~/.kube/config?

**Comment by iocanel** [comment] 2016-09-23 08:42
Of course it does! And its able to even create the namespace.

**Comment by lordofthejars** [comment] 2016-09-23 08:43
then can you try with minishift do:

./minishift start
oc login admin admin
Execute cube test

**Comment by iocanel** [comment] 2016-09-23 15:10
@cmoulliard: try removing arquillian-cube-openshift from your project and tell me if you have any better luck.

**Comment by lordofthejars** [comment] 2016-09-23 16:04
I will try to run ftest as well against a minishift since I think that should work with minishift as well.

**Comment by iocanel** [comment] 2016-09-23 16:20
That would be great! My head is about to explode and I am not sure anymore of what works where. :-D

**Comment by cmoulliard** [comment] 2016-09-24 10:22
I have been able to reproduce the issue from the master branch of my project. So this error comes when we are authenticated with a user "example -> swarm-dev" which is not admin & we  have selected a namespace different from default before to execute the test. 

I have updated the master branch which is working now using the default namespace and admin as user -> see commands & tests executed -> https://github.com/redhat-microservices/quick_swarm_camel-test#all-the-steps-to-execute-to-test-quickstart

**Comment by lordofthejars** [comment] 2016-09-26 17:38
@iocanel any idea on how we can improve this? When running oc login what it is happening is that in .kube/config a new token to connect to the cluster is created.
Do you think that we could hardcode a user and password in config file? Something like:

```
users:
- name: myself
  user:
    password: admin
    username: admin
```

I think it should work, if not in case of minishift we will need to to the `oc login ` each time.

**Comment by lordofthejars** [comment] 2016-09-26 17:42
BTW @iocanel one question has it sense to create every time a new namespace for each run? I mean could we reuse the default namespace and just add a boolean which set to true implies creating a new namespace every time. What do you think?

On Wed I will try to spend one morning on this issue.

**Comment by iocanel** [comment] 2016-09-26 17:57
It's configurable already. You can use an existing namespace if you want. You can also ask not to cleanup when done, so you can troubleshoot etc.

**Comment by cmoulliard** [comment] 2016-09-27 06:31
> Do you think that we could hardcode a user and password in config file? Something like:

You can define a username & password using oc or kubectl go client "http://kubernetes.io/docs/user-guide/kubectl/kubectl_config_set-credentials/"

```
oc config set-credentials myself --username=admin --password=admin

Result

 more ~/.kube/config
...
- name: myself
  user:
    password: admin
    username: admin
```

**Comment by lordofthejars** [comment] 2016-09-27 13:00
Oh nice :). So can I close this issue?

**Comment by cmoulliard** [comment] 2016-09-27 13:03
It can be closed at the condition that the documentation will explain how to deal with namespace, authentication, ....

**Comment by iocanel** [comment] 2016-09-27 14:50
Now I lost you both!

Does it work for you if you use `oc` to set credentials?

**Comment by lordofthejars** [comment] 2016-09-27 15:40
I think so :). As I said in previous previous message it was a matter of configuring correctly `.kube/config`. Using oc is a way to do it :)

**Comment by iocanel** [comment] 2016-09-27 15:43
Ok, I think that my case is different, then.

**Comment by iocanel** [comment] 2016-09-27 15:43
We can close it, and I'll open a new issue specific to my issue.

**Comment by lordofthejars** [comment] 2016-09-27 15:45
Don't want to close because I would like to improve the document with a
WARNING with this use case.

El dt., 27 set. 2016 a les 17:43, Ioannis Canellos (<
notifications@github.com>) va escriure:

**Comment by lordofthejars** [comment] 2016-09-28 17:01
I have improved the documentation so users can avoid the same problem as @cmoulliard found regarding authentication. https://github.com/arquillian/arquillian-cube/commit/e1c3b60bdfed9ea32d56e4abec6d2141b06980af

**Closed by lordofthejars** 2016-09-28 17:01 UTC
Labels: help wanted, kubernetes
