### ISSUE TITLE
Could not run @AfterSuite when using OpenShift Online

### ISSUE THREAD

**Issue by cescoffier** [arquillian/arquillian-cube#585] opened 2017-02-17 12:15 UTC
##### Issue Overview

Surefire failures when running Kubernetes test against an Openshift instance with limited permission (Openshift Online).

##### Expected Behaviour

The tests have been successfully executed. But the build fails, because in the @AfterSuite, it tries to modify the project (removing / adding a label ?). 

I'm using the following ENV variables: 

* NAMESPACE_USE_EXISTING=vertx-it
* ENV_INIT_ENABLED=false

##### Current Behaviour

```
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14:42 min
[INFO] Finished at: 2017-02-17T11:55:49+01:00
[INFO] Final Memory: 62M/939M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:integration-test (default) on project embedded-http: Execution default of goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:integration-test failed: There was an error in the forked process
[ERROR] org.apache.maven.surefire.testset.TestSetFailedException: java.lang.RuntimeException: Could not run @AfterSuite
[ERROR] at org.apache.maven.surefire.common.junit4.JUnit4RunListener.rethrowAnyTestMechanismFailures(JUnit4RunListener.java:209)
[ERROR] at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:169)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
[ERROR] Caused by: java.lang.RuntimeException: Could not run @AfterSuite
[ERROR] at org.jboss.arquillian.junit.Arquillian$1.shutdown(Arquillian.java:159)
[ERROR] at org.jboss.arquillian.junit.Arquillian$1.testRunFinished(Arquillian.java:133)
[ERROR] at org.junit.runner.notification.SynchronizedRunListener.testRunFinished(SynchronizedRunListener.java:42)
[ERROR] at org.junit.runner.notification.RunNotifier$2.notifyListener(RunNotifier.java:103)
[ERROR] at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
[ERROR] at org.junit.runner.notification.RunNotifier.fireTestRunFinished(RunNotifier.java:100)
[ERROR] at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:166)
[ERROR] ... 3 more
[ERROR] Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://api.preview.openshift.com/api/v1/namespaces/vertx-it. Message: Forbidden! User cescoffier/api-preview-openshift-com:443 doesn't have permission..
[ERROR] at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:318)
[ERROR] at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:265)
[ERROR] at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:237)
[ERROR] at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230)
[ERROR] at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handlePatch(OperationSupport.java:221)
[ERROR] at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handlePatch(BaseOperation.java:704)
[ERROR] at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$3.apply(HasMetadataOperation.java:134)
[ERROR] at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$3.apply(HasMetadataOperation.java:130)
[ERROR] at io.fabric8.kubernetes.api.model.DoneableNamespace.done(DoneableNamespace.java:26)
[ERROR] at io.fabric8.kubernetes.api.model.DoneableNamespace.done(DoneableNamespace.java:5)
[ERROR] at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.patch(HasMetadataOperation.java:141)
[ERROR] at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$1.apply(HasMetadataOperation.java:51)
[ERROR] at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$1.apply(HasMetadataOperation.java:41)
[ERROR] at io.fabric8.kubernetes.api.model.DoneableNamespace.done(DoneableNamespace.java:26)
[ERROR] at org.arquillian.cube.kubernetes.impl.namespace.DefaultNamespaceService.annotate(DefaultNamespaceService.java:55)
[ERROR] at org.arquillian.cube.kubernetes.impl.SessionCreatedListener.cleanupSession(SessionCreatedListener.java:177)
[ERROR] at org.arquillian.cube.kubernetes.impl.SessionCreatedListener.stop(SessionCreatedListener.java:158)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
[ERROR] at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
[ERROR] at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
[ERROR] at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
[ERROR] at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
[ERROR] at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
[ERROR] at org.arquillian.cube.kubernetes.impl.SuiteListener.stop(SuiteListener.java:49)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
[ERROR] at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
[ERROR] at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
[ERROR] at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
[ERROR] at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
[ERROR] at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
[ERROR] at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
[ERROR] at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
[ERROR] at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.afterSuite(EventTestRunnerAdaptor.java:80)
[ERROR] at org.jboss.arquillian.junit.Arquillian$1.shutdown(Arquillian.java:146)
[ERROR] ... 9 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

##### Steps To Reproduce

Run any Kubernetes tests against OpenShift Online (https://console.preview.openshift.com)

**Comment by lordofthejars** [comment] 2017-02-17 14:44
Probably cleaning resources like namespace created. @iocanel any workaround for this?

**Comment by iocanel** [comment] 2017-02-17 14:50
I think that this has been fixed as part of  https://github.com/arquillian/arquillian-cube/commit/b34e6c9209492424432a04cf1688dd73f04f00f0.


Will check when I get back home!

**Comment by lordofthejars** [comment] 2017-02-17 14:51
Ok then latest Alpha should contain the fix

**Comment by cescoffier** [comment] 2017-02-17 14:59
I'm using 1.0.0.Alpha18.

**Comment by iocanel** [comment] 2017-02-17 16:26
Ok, then I'll have a look during the weekend.

**Comment by iocanel** [comment] 2017-02-18 12:56
I think that the problem is that the OpenshiftNamespaceService does not override the annotate() method. 
This results in `trying to annotate the namespace instead of the project` which causes a permission issue.

I'll fix the OpenshiftNamespaceService asap.

**Comment by lordofthejars** [comment] 2017-02-20 11:33
@cescoffier Fixed and this is going to be released in Alpha19 during this week. It would be awesome to have some screenrecording/blog post about this use case because I think it is really interesting for K8s + OpenShift users.

**Closed by lordofthejars** 2017-02-20 11:33 UTC

**Comment by cescoffier** [comment] 2017-02-20 12:42
Thanks @lordofthejars and @iocanel ! Awesome work. I will continue migrating my test suite to Cube Arquillian (and open issues if needed ;-)). I can write a blog post or do some screen recording when I've something that I would consider as "done".

I'm working on this test suite: https://github.com/cescoffier/vertx-openshift-it
