### ISSUE TITLE
Alignement with Docker 1.10 release

### ISSUE THREAD

**Issue by smiklosovic** [arquillian/arquillian-cube#268] opened 2016-01-27 16:20 UTC
Hello,

I am looking forward to Docker 1.10 with significant network improvements as static setting of containers IP address via --ip property.

I would like to know how you are about the alignement with 1.10? Is there a lot of changes to cover? When it comes to that --ip feature which is quite important to me, how does this propagate to Cube? Is there a need to implement that somehow or it is automatically picked by Docker's client API when specified in dockerContainers property?

What is the roadmap for Alpha8 release anyway?

Thanks for info

**Comment by aslakknutsen** [comment] 2016-01-27 16:23
Alpha8 is out.. :)
http://arquillian.org/blog/2016/01/21/arquillian-cube-1-0-0-Alpha8/

**Comment by smiklosovic** [comment] 2016-01-27 16:24
Ah, I meant Alpha9 :)

**Comment by smiklosovic** [comment] 2016-01-27 16:25
Alpha9 will resolve downloading of images from private repository which is quite important for me as well.

**Comment by aslakknutsen** [comment] 2016-01-27 16:38
@smiklosovic When ever you stop finding blocking issues for you :)

**Comment by lordofthejars** [comment] 2016-01-27 17:32
@smiklosovic @aslakknutsen yes Alpha9 is going to fix private repos. We can release it after I implement how to set await strategies when using Docker-Compose.

About new network thing, there is two things, the first one is that it is implemented in current snapshot of docker-java, so we need to wait. Also there is an issue https://github.com/arquillian/arquillian-cube/issues/190 opened to discuss about this. My first idea was to let users configure network as they need but all the await thing should continue work thorough docker-host.

**Comment by smiklosovic** [comment] 2016-01-27 20:14
Technically speaking I do not depend on that static IP so much and it can be done via domain names in /etc/hosts right now but it is quite important feature in a long run. Pulling images from private repository is not a blocker for me as well because it can be always downloaded manually beforehand.

I have saw the other PR with automatic Docker machine thingy and it would be nice to have Alpha9 out when that gets merged.

I heard some rumors that Docker is going to be released in later February.

**Comment by eddumelendez** [comment] 2016-01-27 22:41
@smiklosovic yes docker 1.10 will be released the next week. [Docker Roadmap](https://github.com/docker/docker/wiki)

**Comment by smiklosovic** [comment] 2016-02-06 12:53
sweet, It's out! 

https://github.com/docker/docker/releases/tag/v1.10.0

Lets see how many things this will break :)

**Comment by smiklosovic** [comment] 2016-02-12 16:35
I have update to 1.10 and nothing is broken so far.

**Comment by lordofthejars** [comment] 2016-02-12 16:43
Cool :) now the problem is adapting new docker-compose format

**Comment by aslakknutsen** [comment] 2016-02-12 16:47
Excellent

**Comment by smiklosovic** [comment] 2016-02-12 18:15
In the end there are these two errors when mvn installing

`Tests run: 15, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.235 sec <<< FAILURE! - in org.arquillian.cube.docker.impl.client.CubeConfiguratorTest
shouldUseDefaultsInCaseOfNotHavingDockerMachineInstalledAndNoDockerUriNorMachineName(org.arquillian.cube.docker.impl.client.CubeConfiguratorTest)  Time elapsed: 0.021 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: map containing ["serverUri"->"https://192.168.0.1:2376"]
     but: map was [<serverUri=unix:///var/run/docker.sock>, <certPath=/home/smikloso/.boot2docker/certs/boot2docker-vm>, <dockerServerIp=localhost>]
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.arquillian.cube.docker.impl.client.CubeConfiguratorTest.shouldUseDefaultsInCaseOfNotHavingDockerMachineInstalledAndNoDockerUriNorMachineName(CubeConfiguratorTest.java:216)

shouldNotUseDockerMachineIfDockerHostIsNotSetNotDockerMachineAndTwoMachineIsRunning(org.arquillian.cube.docker.impl.client.CubeConfiguratorTest)  Time elapsed: 0.01 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: map containing ["serverUri"->"https://192.168.0.1:2376"]
     but: map was [<serverUri=unix:///var/run/docker.sock>, <certPath=/home/smikloso/.boot2docker/certs/boot2docker-vm>, <dockerServerIp=localhost>]
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.arquillian.cube.docker.impl.client.CubeConfiguratorTest.shouldNotUseDockerMachineIfDockerHostIsNotSetNotDockerMachineAndTwoMachineIsRunning(CubeConfiguratorTest.java:199)
`

I am not sure if this is 1.10 specific or it was broken before as well

I was trying firstly to run with 1.10 what I have implemented in a standalon-ish way and that works ...

**Comment by smiklosovic** [comment] 2016-02-12 18:18
I do have docker machine installed so when I understand that correctly, that test counts on the fact that I do not have it installed? If this is true, I would do some JUnit Assume in that test.

**Comment by smiklosovic** [comment] 2016-02-12 21:32
https://github.com/arquillian/arquillian-cube/pull/289

**Comment by smiklosovic** [comment] 2016-02-12 22:20
this one was spotted afterwards https://github.com/arquillian/arquillian-cube/issues/290

Sorry for the buzz ... I was thinking it would be more smooth transition towards 1.10.

**Comment by lordofthejars** [comment] 2016-03-18 14:53
We have moved to Docker-Java 3 which is the one that supported Docker 1.10. Next steps will be opening issues for supporting new Docker Compose format, Network, Volumes, ...

**Closed by lordofthejars** 2016-03-18 14:53 UTC
